### ISSUE TITLE
Derive from pre-GPL license

### ISSUE THREAD

**Issue by jebw** [jellybob/mimemagic#2]
This code base is currently a fork from tip of master, which includes the GPL changes - since you cannot relicense from GPL to MIT, it should fork prior to relicense.

eg 40dd02bb6b442535f97c35326c0383bc67146ac4 for `master` or `01f92d86d15d85cfd0f20dabd025dcbd36a8a60f` for 0.3 branch

**Comment by jellybob** [comment]
Thanks, will be doing so.

**Comment by pboling** [comment]
@jebw In this case we _can relicense_ with the caveats that we have the author's permission for the code which will be relicensed (and @jellybob does), and we remove all of the offending GPL code that can't be relicensed without permission (and @jellybob is).
